Repository O-market/O-market, pull requests merged in 2022-11, with the labels that each got.

#51 [D-2] 다중선택 ImagePicker 및 상품 등록 기능 구현
  Projects/ODesignSystem/Sources/Component/ODSPhotoButtonView.swift
  Projects/ODesignSystem/Sources/Component/ODSXMarkButton.swift
  Projects/OmarketApp/Sources/Data/Network/Infrastructure/EndpointAPI.swift
  Projects/OmarketApp/Sources/Domain/Entity/ImageData.swift
  Projects/OmarketApp/Sources/Domain/Entity/ProductRequest.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/Create/Coordinator/CreateCoordinator.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/Create/View/CreateView.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/Create/View/ImageView.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/Create/ViewController/CreateViewController.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/Create/ViewModel/CreateViewModel.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/Detail/View/DetailView.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/Detail/ViewModel/DetailViewModel.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/Detail/ViewModel/DetailViewModelItem.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/Delegates/MSImagePickerDelegate.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/MSImagePicker.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/Model/MSAssetItem.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/Model/MSImageManager.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/Model/MSPickerSettings.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/View/MSImageCell.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/View/MSImagePickerView.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/View/MSSelectionIndicator.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ProductCell/ProductCell.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ProductCell/ProductCellViewModel.swift
  Projects/OmarketApp/Sources/Utils/Extension/UIAlertController+Extension.swift
  Projects/OmarketApp/SupportingFiles/OmarketApp-Info.plist
  Projects/OmarketApp/Tests/TestDouble/Stub/StubProductFetchUseCaseImpl.swift
  Projects/OmarketApp/Tests/ViewModelTests/CreateViewModelTest.swift
  Projects/OmarketApp/Tests/ViewModelTests/DetailViewModelTest.swift
Labels: D-N

#53 [D-3] 메인, 상품목록 화면 코드 리팩토링
  Projects/OmarketApp/Sources/Presentation/Main/Coordinator/MainCoordinator.swift
  Projects/OmarketApp/Sources/Presentation/Main/View/MainEventCell.swift
  Projects/OmarketApp/Sources/Presentation/Main/View/MainProductHeader.swift
  Projects/OmarketApp/Sources/Presentation/Main/ViewController/MainViewController.swift
  Projects/OmarketApp/Sources/Presentation/Main/ViewModel/MainEventCellViewModel.swift
  Projects/OmarketApp/Sources/Presentation/Main/ViewModel/MainViewModel.swift
  Projects/OmarketApp/Sources/Presentation/Main/ViewModel/ProductSection.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ProductCell/TestCollectionViewController.swift
  Projects/OmarketApp/Sources/Presentation/Product/Coordinator/ProductCoordinator.swift
  Projects/OmarketApp/Sources/Presentation/Product/View/ProductCell.swift
  Projects/OmarketApp/Sources/Presentation/Product/View/ProductView.swift
  Projects/OmarketApp/Sources/Presentation/Product/ViewController/ProductViewController.swift
  Projects/OmarketApp/Sources/Presentation/Product/ViewModel/ProductCellViewModel.swift
  Projects/OmarketApp/Sources/Presentation/Product/ViewModel/ProductViewModel.swift
  Projects/OmarketApp/Sources/Presentation/Splash/Coordinator/SplashCoordinator.swift
  Projects/OmarketApp/Sources/Presentation/Splash/ViewController/SplashViewController.swift
Labels: refactor

#55 [D-2] 네트워크 PATCH 기능 구현
  Projects/OmarketApp/Sources/Data/Network/Infrastructure/EndpointAPI.swift
  Projects/OmarketApp/Sources/Data/Repository/ProductRepositoryImpl.swift
  Projects/OmarketApp/Sources/Domain/Interface/Repository/ProductRepository.swift
  Projects/OmarketApp/Sources/Domain/UseCase/ProductFetchUseCase.swift
Labels: feature, D-N

#57 [D-2] Create 네이밍 수정 및 폴더 위치 수정
  Projects/OmarketApp/Sources/Presentation/Product/Coordinator/ProductCoordinator.swift
  Projects/OmarketApp/Sources/Presentation/Writing/Coordinator/CreationCoordinator.swift
  Projects/OmarketApp/Sources/Presentation/Writing/View/ImageView.swift
  Projects/OmarketApp/Sources/Presentation/Writing/View/WritingView.swift
  Projects/OmarketApp/Sources/Presentation/Writing/ViewController/CreationViewController.swift
  Projects/OmarketApp/Sources/Presentation/Writing/ViewModel/CreationViewModel.swift
  Projects/OmarketApp/Tests/ViewModelTests/CreateViewModelTest.swift
Labels: refactor, D-N

#62 [D-2] MSImagePicker -> SFImagePicker로 대체
  Projects/OmarketApp/Project.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/Delegates/MSImagePickerDelegate.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/MSImagePicker.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/Model/MSAssetItem.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/Model/MSImageManager.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/Model/MSPickerSettings.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/View/MSImageCell.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/View/MSImagePickerView.swift
  Projects/OmarketApp/Sources/Presentation/MainScene/ImagePicker/View/MSSelectionIndicator.swift
  Projects/OmarketApp/Sources/Presentation/Writing/Coordinator/CreationCoordinator.swift
  Projects/OmarketApp/Sources/Presentation/Writing/View/ProductImageView.swift
  Projects/OmarketApp/Sources/Presentation/Writing/View/WritingView.swift
  Projects/OmarketApp/Sources/Presentation/Writing/ViewController/CreationViewController.swift
  Projects/OmarketApp/Sources/Presentation/Writing/ViewController/EditingViewController.swift
  Projects/OmarketApp/Sources/Presentation/Writing/ViewModel/CreationViewModel.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Dependency+Extension.swift
Labels: refactor, D-N

#63 [D-3] 상품 상세 화면 리팩토링
  Projects/OmarketApp/Sources/Presentation/Detail/Coordinator/DetailCoordinator.swift
  Projects/OmarketApp/Sources/Presentation/Detail/View/DetailView.swift
  Projects/OmarketApp/Sources/Presentation/Detail/View/ProductImageCell.swift
  Projects/OmarketApp/Sources/Presentation/Detail/ViewController/DetailViewController.swift
  Projects/OmarketApp/Sources/Presentation/Detail/ViewModel/DetailViewModel.swift
  Projects/OmarketApp/Sources/Presentation/Detail/ViewModel/DetailViewModelItem.swift
Labels: refactor, D-N

#65 [D-2] 상품 Cell의 각각의 UI 요소들이 겹치는 문제 수정
  Projects/ODesignSystem/Sources/Foundation/ODSIcon.swift
  Projects/OmarketApp/Sources/Presentation/Main/View/MainProductHeader.swift
  Projects/OmarketApp/Sources/Presentation/Main/ViewController/MainViewController.swift
  Projects/OmarketApp/Sources/Presentation/Main/ViewModel/MainViewModel.swift
  Projects/OmarketApp/Sources/Presentation/Product/Coordinator/ProductCoordinator.swift
  Projects/OmarketApp/Sources/Presentation/Product/View/BadgeProductCell/BadgeProductCell.swift
  Projects/OmarketApp/Sources/Presentation/Product/View/BadgeProductCell/BadgeProductCellContentView.swift
  Projects/OmarketApp/Sources/Presentation/Product/View/ProductCell/ProductCell.swift
  Projects/OmarketApp/Sources/Presentation/Product/View/ProductCell/ProductCellContentView.swift
  Projects/OmarketApp/Sources/Presentation/Product/View/ProductView.swift
  Projects/OmarketApp/Sources/Presentation/Product/View/StockProductCell/StockProductCell.swift
  Projects/OmarketApp/Sources/Presentation/Product/View/StockProductCell/StockProductCellContentView.swift
  Projects/OmarketApp/Sources/Presentation/Product/ViewController/ProductViewController.swift
  Projects/OmarketApp/Sources/Presentation/Product/ViewModel/ProductCellViewModel.swift
  Projects/OmarketApp/Sources/Presentation/Product/ViewModel/ProductViewModel.swift
  Projects/OmarketApp/Sources/Presentation/Writing/ViewController/CreationViewController.swift
  Projects/OmarketApp/Sources/Presentation/Writing/ViewController/EditingViewController.swift
  Projects/OmarketApp/Sources/Utils/Extension/NotificationName+Extension.swift
Labels: feature, D-N

#68 [D-0] 로고 및 앱 아이콘 변경
  Projects/ODesignSystem/Sources/Foundation/ODSColor.swift
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Projects/OmarketApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/OmarketApp/Resources/Assets.xcassets/Logo.imageset/Contents.json
  Projects/OmarketApp/Resources/Assets.xcassets/Logo.imageset/Logo-1.png
  Projects/OmarketApp/Resources/Assets.xcassets/Logo.imageset/Logo-2.png
  Projects/OmarketApp/Resources/Assets.xcassets/Logo.imageset/Logo.png
  Projects/OmarketApp/Resources/Assets.xcassets/Logo.imageset/OMK 1.png
  Projects/OmarketApp/Resources/Assets.xcassets/Logo.imageset/OMK 2.png
  Projects/OmarketApp/Resources/Assets.xcassets/Logo.imageset/OMK.png
  Projects/OmarketApp/Resources/LaunchScreen.storyboard
  Projects/OmarketApp/Sources/Presentation/Splash/ViewController/SplashViewController.swift
  Projects/OmarketApp/Sources/Presentation/Writing/ViewController/CreationViewController.swift
Labels: D-0

#69 [D-2] 상품 검색 기능 추가
  Projects/ODesignSystem/Sources/Foundation/ODSIcon.swift
  Projects/OmarketApp/Sources/Application/Coordinator/AppCoordinator.swift
  Projects/OmarketApp/Sources/Data/Network/Infrastructure/EndpointAPI.swift
  Projects/OmarketApp/Sources/Domain/UseCase/ProductFetchUseCase.swift
  Projects/OmarketApp/Sources/Presentation/Search/Coordinator/SearchCoordinator.swift
  Projects/OmarketApp/Sources/Presentation/Search/View/SearchCell.swift
  Projects/OmarketApp/Sources/Presentation/Search/View/SearchView.swift
  Projects/OmarketApp/Sources/Presentation/Search/ViewController/SearchViewController.swift
  Projects/OmarketApp/Sources/Presentation/Search/ViewModel/SearchCellViewModel.swift
  Projects/OmarketApp/Sources/Presentation/Search/ViewModel/SearchViewModel.swift
  README.md
Labels: D-N

#72 [D-3] 상품 삭제를 위한 API 및 기능 구현
  Projects/OmarketApp/Sources/Data/Network/Infrastructure/EndpointAPI.swift
  Projects/OmarketApp/Sources/Data/Repository/ProductRepositoryImpl.swift
  Projects/OmarketApp/Sources/Domain/Interface/Repository/ProductRepository.swift
  Projects/OmarketApp/Sources/Domain/UseCase/ProductFetchUseCase.swift
  Projects/OmarketApp/Sources/Presentation/Detail/ViewController/DetailViewController.swift
  Projects/OmarketApp/Sources/Presentation/Detail/ViewModel/DetailViewModel.swift
  Projects/OmarketApp/Tests/RepositoryTests/ProductRepositoryTests.swift
  Projects/OmarketApp/Tests/TestDouble/Mock/MockProductRepositoryImpl.swift
  Projects/OmarketApp/Tests/TestDouble/Stub/StubProductFetchUseCaseImpl.swift
  Projects/OmarketApp/Tests/UseCaseTests/ProductFetchUseCaseTests.swift
  Projects/OmarketApp/Tests/ViewModelTests/CreateViewModelTest.swift
Labels: feature, D-N

#74 [D-2] Creation 리팩토링
  Projects/OmarketApp/Sources/Presentation/Writing/View/WritingView.swift
  Projects/OmarketApp/Sources/Presentation/Writing/ViewController/CreationViewController.swift
  Projects/OmarketApp/Sources/Presentation/Writing/ViewModel/CreationViewModel.swift
  Projects/OmarketApp/Tests/ViewModelTests/CreateViewModelTest.swift
Labels: refactor, D-N
